### ISSUE TITLE
Escape button stops working when connection to keyboard is lost and back.

### ISSUE THREAD

**Issue by desmax** [dnicolson/BluetoothKeyboardEnhancer#1]
Anything I can do about it? somehow restart the service when keyboard is connected?

**Comment by dnicolson** [comment]
Can you describe how the connection is lost? As long as there is a Bluetooth connection HDI events should work, do other keys on the keyboard work? What application are you using the escape key in?

**Comment by desmax** [comment]
@dnicolson when keyboard is inactive for around 10 mins it turns off bluetooth for energy saving reasons(mac shows "connection lost" on a screen), then I press any key and keyboard starts to work again, but escape button does not. I run `brew services start bluetoothkeyboardenhancer` and its back again.

>What application are you using the escape key in?

for example I open spolight search and press Esc

**Comment by dnicolson** [comment]
Do you see `bke` running in Activity Monitor? What is the output of `brew services start bluetoothkeyboardenhancer`? Do you see anything in Console when filtering for `bke`?

**Comment by desmax** [comment]
@dnicolson 

>Do you see bke running in Activity Monitor?

yes

>What is the output of brew services start bluetoothkeyboardenhancer?

it says its already started

>Do you see anything in Console when filtering for bke?

two events, when turn on\off my keyboard
`HIDAnalytics Unregister Send event com.apple.hid.queueUsage`
`Received configuration update from daemon (initial)`

**Comment by desmax** [comment]
@dnicolson to be specific those events appear only when I turn my keyboard off

**Comment by dnicolson** [comment]
If `bke` is already running `brew services start bluetoothkeyboardenhancer` should not have any effect.

Are you running Catalina? Do you have the correct security settings in System Preferences?

**Comment by desmax** [comment]
@dnicolson sorry, I meant RESTART instead of start. so if I run restart everything starts to work
>Are you running Catalina? Do you have the correct security settings in System Preferences?

yes, catalina. yes, I believe so

**Comment by dnicolson** [comment]
Is there anything that could seize control of the keyboard input, Karabiner perhaps?

**Comment by desmax** [comment]
@dnicolson thats it! I installed Karabiner before I found this app and forgot to delete it. Thank you for your time and for this amazing tool :)
