### ISSUE TITLE
Escape key stop working

### ISSUE THREAD

**Issue by francofadini** [dnicolson/BluetoothKeyboardEnhancer#2]
kbe is running. I have seen this [issue](https://github.com/dnicolson/BluetoothKeyboardEnhancer/issues/1)
- I have no other tool installed.
- None tool is asking for keyboard Input Monitoring permissions
- I have allowed bke in Accessibility and Input Monitoring
- Im running macOS Catalina

I can see this error on the console when starting the service
`{ID: <ID of InvalidCode>, PID[4666], auid: 502, euid: 502, binary path: '/usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke'} attempted to call TCCAccessRequest without the com.apple.private.tcc.manager.check-by-audit-token entitlement`

**Comment by dnicolson** [comment]
That warning is normal actually. What application are you using the escape key with?

I know that the escape key will not work in the Simulator app because keyboard capturing works at the IOHID event level, CGEvents are not seen or responded to. I'm not aware of any other apps like this.

**Comment by francofadini** [comment]
Hey @dnicolson! Thanks for this great app, and your quick support!
My main testing is opening the spotlight search, and trying to close it with the escape key. Im also testing opt+command+escape in order to see force quit panel.

- Emojis command is working ok

Console log after force quit:
```
predeterminado	10:01:52.037832-0300	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:bke, _appTrackingState = 2

predeterminado	10:01:52.109291-0300	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke, type: 1: 0x7fc42a02b4b0 at /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke

predeterminado	10:01:52.154855-0300	bke	HIDAnalytics Timer Send event com.apple.hid.queueUsage
error	10:01:52.162516-0300	tccd	{ID: <ID of InvalidCode>, PID[6054], auid: 502, euid: 502, binary path: '/usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke'} attempted to call TCCAccessRequest without the com.apple.private.tcc.manager.check-by-audit-token entitlement

predeterminado	10:01:52.166048-0300	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke, type: 1: 0x7fc428612360 at /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke
```

Console log after pressing the escape key:

```
predeterminado	10:01:59.722464-0300	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke, type: 1: 0x7fc4285256f0 at /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke

predeterminado	10:01:59.761843-0300	bke	FRONTLOGGING: version 1

predeterminado	10:01:59.761871-0300	bke	Registering, pid=6054

predeterminado	10:01:59.762535-0300	bke	CHECKIN: pid=6054

predeterminado	10:01:59.767868-0300	bke	CHECKEDIN: pid=6054 asn=0x0-0xa90a9 foreground=0

predeterminado	10:01:59.769361-0300	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : bke

predeterminado	10:01:59.772171-0300	bke	Registered, pid=6054 ASN=0x0,0xa90a9

predeterminado	10:01:59.772389-0300	bke	Registered, pid=6054 cgConnectionID=51157

predeterminado	10:01:59.778418-0300	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke, type: 1: 0x7fc4285256f0 at /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke

predeterminado	10:01:59.786252-0300	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke, type: 1: 0x7fc42842ba50 at /usr/local/Cellar/bluetoothkeyboardenhancer/0.3.0/bin/bke
```

**Comment by francofadini** [comment]
@dnicolson The problem was solved, after using the MacBook Pro escape button. I don't know why haha.

**Comment by dnicolson** [comment]
Force quit shouldn't work as there is no support for modifier keys, I will look into adding it.

Spotlight works most of the time, I noticed sometimes it triggers a system beep instead you need to enter a character then hit escape twice to close. It seems to occur after trying to use force quit from the Bluetooth keyboard.

**Comment by francofadini** [comment]
I will close it, as it is working now! Thanks!
