### ISSUE TITLE
When using the brew method to install, I get a SHA256 verification check issue

### ISSUE THREAD

**Issue by aubreypwd** [dnicolson/BluetoothKeyboardEnhancer#3]
The only way I could install it was using `brew edit dnicolson/bluetoothkeyboardenhancer/bluetoothkeyboardenhancer` and disable the SHA line in the config file...

**Comment by dnicolson** [comment]
Thanks for reporting!

I've fixed the hash and in case the old tap is still around you can fix it with:
```
cd /usr/local/Homebrew/Library/Taps/dnicolson/homebrew-bluetoothkeyboardenhancer
git fetch
git reset --hard origin/master
```
